/*
 * This file was generated by the Gradle 'init' task.
 */

allprojects {
    group = "org.example"
    version = "1.0-SNAPSHOT"

    plugins {
        id("java")
        id("maven-publish")
    }
}


subprojects {

    dependencies {
        implementation group: 'io.netty', name: 'netty-all', version: '4.1.51.Final'
    }


    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }

    compileJava {
        sourceCompatibility = 11
        targetCompatibility = 11
    }

    compileTestJava {
        sourceCompatibility = 11
        targetCompatibility = 11
    }

    publishing {
        publications {
            maven(MavenPublication) {
                from(components.java)
            }
        }
    }
}