/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "NetworkProgramming"
include("NettyServer")
include("NettyClient")
include("ReactorTcpClient")
include("ReactorTcpServer")
include("ReactiveProgramming")